version: "3"

services:
  posteio:
    image: analogic/poste.io
    ports:
      - 0.0.0.0:25:25       
      - 80:80
      - 110:110
      - 143:143
      - 443:443
      - 465:465
      - 587:587
      - 993:993
      - 995:995
      - 4190:4190
    volumes:
      - ./posteio:/data     
    hostname: mail
    domainname: smartdom.ch 
    environment:
      - TZ=Europe/Prague
